spring:
  application:
    name: 'auth-service'
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: '${DB_URL}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
    fetchRegistry: true
    healthcheck:
      enabled: true
    jersey:
      enabled: false
    restclient:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    com.innowise.authservice.service.client.UserServiceClient: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
        exclude: errors
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_EXPORT_SERVER}/v1/traces
    logging:
      export:
        otlp:
          endpoint: ${OTLP_EXPORT_SERVER}/v1/logs
  otlp:
    metrics:
      export:
        url: ${OTLP_EXPORT_SERVER}/v1/metrics

resilience4j:
  timelimiter:
    configs:
      UserServiceClient:
        timeoutDuration: 3s
        cancelRunningFuture: true
  retry:
    configs:
      UserServiceClient:
        maxAttempts: 3
        waitDuration: 1s

  circuitbreaker:
    configs:
      UserServiceClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

