spring:
  application:
    name: 'auth-service'
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: '${DB_URL}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
    fetchRegistry: true
    healthcheck:
      enabled: true
    jersey:
      enabled: false
    restclient:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10