spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: register
              uri: lb://auth-service
              predicates:
                - 'Path=/api/v1/auth/register'
            - id: login
              uri: lb://auth-service
              predicates:
                - 'Path=/api/v1/auth/login'
            - id: refresh
              uri: lb://auth-service
              predicates:
                - 'Path=/api/v1/auth/refresh'
            - id: user-service
              uri: lb://user-service
              predicates:
                - 'Path=/api/v1/users/**'
              filters:
                - 'Authorization'
                - 'CircuitBreaker=user-service'
            - id: order-service
              uri: lb://order-service
              predicates:
                - 'Path=/api/v1/orders/**'
              filters:
                - 'Authorization'
                - 'CircuitBreaker=order-service'
            - id: others
              uri: no://op
              predicates:
                - 'Path=**'
              filters:
                - 'SetStatus=NOT_FOUND'
          discovery:
            locator:
              enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        ignore-exceptions:
          - com.innowise.common.exception.ExternalApiException
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3
        cancel-running-future: true
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 1
        ignore-exceptions:
          - com.innowise.common.exception.ExternalApiException

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers

server:
  port: 8090

logging:
  level:
    org.springframework.cloud.circuitbreaker.*: DEBUG
    io.github.resilience4j.*: DEBUG