services:
  discovery-service:
    image: discovery-service:latest
    build:
      context: ..
      dockerfile: discovery-service/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    environment:
      - SERVER_PORT=${SERVER_PORT}
#    ports:
#      - "8762:${SERVER_PORT}"
