spring:
  application:
    name: 'user-service'
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: '${DB_URL}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
  cache:
    type: redis
  data:
    redis:
      host: '${REDIS_HOST}'
      port: '${REDIS_PORT}'
      username: '${REDIS_USER}'
      password: '${REDIS_USER_PASSWORD}'
  jackson:
    default-property-inclusion: non_null

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
  instance:
    prefer-ip-address: true
